# Generated by Django 4.2.3 on 2023-07-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="token",
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
    ]
